# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'note.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_note_app(object):
    def setupUi(self, note_app):
        note_app.setObjectName("note_app")
        note_app.setWindowModality(QtCore.Qt.NonModal)
        note_app.setEnabled(True)
        note_app.setFixedSize(593, 370)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(note_app.sizePolicy().hasHeightForWidth())
        note_app.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/icon.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        note_app.setWindowIcon(icon)
        self.text = QtWidgets.QTextEdit(note_app)
        self.text.setGeometry(QtCore.QRect(10, 50, 571, 300))
        self.text.setObjectName("text")
        self.saveButton = QtWidgets.QPushButton(note_app)
        self.saveButton.setGeometry(QtCore.QRect(380, 10, 201, 23))
        self.saveButton.setObjectName("saveButton")
        self.insert_delete_Button = QtWidgets.QPushButton(note_app)
        self.insert_delete_Button.setGeometry(QtCore.QRect(10, 10, 201, 23))
        self.insert_delete_Button.setObjectName("insert_delete_Button")
        self.savelabel = QtWidgets.QLabel(note_app)
        self.savelabel.setGeometry(QtCore.QRect(220, 10, 151, 21))
        self.savelabel.setText("")
        self.savelabel.setObjectName("savelabel")
        self.labelImage = QtWidgets.QLabel(note_app)
        self.labelImage.setGeometry(10, 360, 571, 300)
        self.labelImage.setScaledContents(True)
        self.labelImage.hide()

        self.retranslateUi(note_app)
        QtCore.QMetaObject.connectSlotsByName(note_app)

    def retranslateUi(self, note_app):
        _translate = QtCore.QCoreApplication.translate
        note_app.setWindowTitle(_translate("note_app", "Note"))
        self.saveButton.setText(_translate("note_app", "Сохранить"))
        self.insert_delete_Button.setText(_translate("note_app", "Загрузить изображение"))
